spring:
  application:
    name: base_project_1.1
  datasource: #Change when dev
    url: 'jdbc:mysql://localhost:3306/pratice_1'
    username: admin
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id:
          new_generator_mappings: true
        show:
          sql: true
        format_sql: true
        hbm2ddl:
          auto: update
auth:
  type: access_token   # jwt | access_token
  jwt:
    secret: secretkeyofJWTcreatedbyhungtd2180
    token-expire: 3600
  access-token:
    token-expire: 3600
    refresh-token-expire: 2592000
  attempt: 5 #times
  retry: 300 #seconds
